name: Process Uploaded Sheet

on:
  repository_dispatch:
    types: [process-sheet-upload]

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Confirm Python Version
        run: |
          echo "Python location: ${{ steps.python.outputs.python-path }}"
          ${{ steps.python.outputs.python-path }}/bin/python --version

      - name: Install dependencies
        run: |
          ${{ steps.python.outputs.python-path }}/bin/python -m pip install --upgrade pip
          ${{ steps.python.outputs.python-path }}/bin/python -m pip install numpy==1.24.4 pandas==1.5.3
          ${{ steps.python.outputs.python-path }}/bin/python -m pip install gspread==5.12.4 gspread-dataframe==3.3.1
          ${{ steps.python.outputs.python-path }}/bin/python -m pip install google-auth==2.29.0 Flask==3.0.3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Run Python Sheet Processor
        run: ${{ steps.python.outputs.python-path }}/bin/python main.py
        env:
          TEMP_SHEET_ID: ${{ github.event.client_payload.tempSheetId }}
          MAIN_SHEET_ID: ${{ github.event.client_payload.mainSheetId }}
          SELECTED_REGIONS: ${{ join(github.event.client_payload.regions, ',') }}
