name: Process Uploaded Sheet

on:
  # This trigger allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tempSheetId:
        description: 'ID of the temporary Google Sheet'
        required: true
      mainSheetId:
        description: 'ID of the main customer list Sheet'
        required: true
      selectedRegions:
        description: 'Comma-separated list of regions (e.g., ALPHA 1,BETA 2)'
        required: true
        
  # This trigger allows your Apps Script to start the workflow via an API call
  repository_dispatch:
    types: [process-sheet-upload]

jobs:
  run-python-script:
    # Runs the job on a Windows machine for maximum compatibility
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sets up a stable version of Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Installs each library individually to prevent conflicts
      - name: Install dependencies
        run: |
          pip install numpy==1.26.4
          pip install pandas==2.2.2
          pip install gspread==5.12.4
          pip install gspread-dataframe==3.3.1
          pip install google-auth==2.29.0
          pip install Flask==3.0.3

      # Authenticates to Google Cloud using your secret
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Runs your script and passes in the data from Apps Script or manual trigger
      - name: Run Python Sheet Processor
        run: python main.py
        env:
          TEMP_SHEET_ID: ${{ github.event.client_payload.tempSheetId || github.event.inputs.tempSheetId }}
          MAIN_SHEET_ID: ${{ github.event.client_payload.mainSheetId || github.event.inputs.mainSheetId }}
          SELECTED_REGIONS: ${{ github.event.client_payload.selectedRegions != '' && github.event.client_payload.selectedRegions || github.event.inputs.selectedRegions }}
