name: Process Uploaded Sheet

on:
  repository_dispatch:
    types: [process-sheet-upload]

jobs:
  run-python-script:
    # This is the only line that has been changed
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install numpy==1.26.4
          pip install pandas==2.2.2
          pip install gspread==5.12.4
          pip install gspread-dataframe==3.3.1
          pip install google-auth==2.29.0
          pip install Flask==3.0.3

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Run Python Sheet Processor
        run: python main.py
        env:
          TEMP_SHEET_ID: ${{ github.event.client_payload.tempSheetId }}
          MAIN_SHEET_ID: ${{ github.event.client_payload.mainSheetId }}
          SELECTED_REGIONS: ${{ join(github.event.client_payload.regions, ',') }}
