name: Process Uploaded Sheet

on:
  workflow_dispatch:
    inputs:
      tempSheetId:
        description: 'ID of the temporary Google Sheet'
        required: true
      mainSheetId:
        description: 'ID of the main customer list Sheet'
        required: true
      selectedRegions:
        description: 'JSON array of regions (e.g., ["ALPHA 1", "BETA 2"])'
        required: true
        
  repository_dispatch:
    types: [process-sheet-upload]

jobs:
  # This is now a single job that runs the Python script once.
  run-python-script:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.26.4 pandas==2.2.2 gspread==5.12.4 gspread-dataframe==3.3.1 google-auth==2.29.0

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Run Python Sheet Processor
        run: python main.py
        env:
          # This passes the full list of regions as a JSON string.
          SELECTED_REGIONS_JSON: ${{ toJSON(github.event.client_payload.regions || fromJSON(github.event.inputs.selectedRegions)) }}
          TEMP_SHEET_ID: ${{ github.event.client_payload.tempSheetId || github.event.inputs.tempSheetId }}
          MAIN_SHEET_ID: ${{ github.event.client_payload.mainSheetId || github.event.inputs.mainSheetId }}
