name: Process Uploaded Sheet

on:
  repository_dispatch:
    types: [process-sheet-upload]

jobs:
  run-python-script:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Clean up cached files (optional but recommended)
        run: |
          pip cache purge || true
          find . -type d -name '__pycache__' -exec rm -r {} +

      - name: Install dependencies (stable versions)
        run: |
          pip install numpy==1.24.4
          pip install pandas==1.5.3
          pip install gspread==5.12.4
          pip install gspread-dataframe==3.3.1
          pip install google-auth==2.29.0
          pip install Flask==3.0.3

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Run Python Sheet Processor
        run: python main.py
        env:
          TEMP_SHEET_ID: ${{ github.event.client_payload.tempSheetId }}
          MAIN_SHEET_ID: ${{ github.event.client_payload.mainSheetId }}
          SELECTED_REGIONS: ${{ join(github.event.client_payload.regions, ',') }}
